// ---------- Vacances scolaires officielles 2026-2027 (zones A, B, C métropole) ----------
// Source : calendrier scolaire officiel du ministère de l'Éducation nationale
// (arrêté du 22-23 octobre 2025 au Journal officiel).
// La date de fin des vacances d'été 2027 n'était pas encore publiée au moment de la
// rédaction : elle est mise ici par défaut au 31 août 2027, à corriger dans les
// réglages dès que la date de rentrée 2027 sera connue (généralement début septembre).

export const ZONES = {
  A: {
    nom: "Zone A (Besançon, Bordeaux, Clermont-Ferrand, Dijon, Grenoble, Limoges, Lyon, Poitiers)",
    vacances: [
      { id: "toussaint", nom: "Vacances de la Toussaint", dateDebut: "2026-10-17", dateFin: "2026-11-02" },
      { id: "noel", nom: "Vacances de Noël", dateDebut: "2026-12-19", dateFin: "2027-01-04" },
      { id: "hiver", nom: "Vacances d'hiver", dateDebut: "2027-02-13", dateFin: "2027-03-01" },
      { id: "printemps", nom: "Vacances de printemps", dateDebut: "2027-04-10", dateFin: "2027-04-26" },
      { id: "pont-ascension", nom: "Pont de l'Ascension", dateDebut: "2027-05-07", dateFin: "2027-05-07" },
      { id: "ete", nom: "Vacances d'été", dateDebut: "2027-07-03", dateFin: "2027-08-31" },
    ],
  },
  B: {
    nom: "Zone B (Aix-Marseille, Amiens, Lille, Nancy-Metz, Nantes, Nice, Normandie, Orléans-Tours, Reims, Rennes, Strasbourg)",
    vacances: [
      { id: "toussaint", nom: "Vacances de la Toussaint", dateDebut: "2026-10-17", dateFin: "2026-11-02" },
      { id: "noel", nom: "Vacances de Noël", dateDebut: "2026-12-19", dateFin: "2027-01-04" },
      { id: "hiver", nom: "Vacances d'hiver", dateDebut: "2027-02-20", dateFin: "2027-03-08" },
      { id: "printemps", nom: "Vacances de printemps", dateDebut: "2027-04-17", dateFin: "2027-05-03" },
      { id: "pont-ascension", nom: "Pont de l'Ascension", dateDebut: "2027-05-07", dateFin: "2027-05-07" },
      { id: "ete", nom: "Vacances d'été", dateDebut: "2027-07-03", dateFin: "2027-08-31" },
    ],
  },
  C: {
    nom: "Zone C (Créteil, Montpellier, Paris, Toulouse, Versailles)",
    vacances: [
      { id: "toussaint", nom: "Vacances de la Toussaint", dateDebut: "2026-10-17", dateFin: "2026-11-02" },
      { id: "noel", nom: "Vacances de Noël", dateDebut: "2026-12-19", dateFin: "2027-01-04" },
      { id: "hiver", nom: "Vacances d'hiver", dateDebut: "2027-02-06", dateFin: "2027-02-22" },
      { id: "printemps", nom: "Vacances de printemps", dateDebut: "2027-04-03", dateFin: "2027-04-19" },
      { id: "pont-ascension", nom: "Pont de l'Ascension", dateDebut: "2027-05-07", dateFin: "2027-05-07" },
      { id: "ete", nom: "Vacances d'été", dateDebut: "2027-07-03", dateFin: "2027-08-31" },
    ],
  },
};

// Jours fériés communs aux trois zones (dates fixes ou calculées à partir de Pâques 2027).
export const FERIES_COMMUNS = [
  { id: "armistice-2026", nom: "Armistice 1918", date: "2026-11-11" },
  { id: "travail-2027", nom: "Fête du travail", date: "2027-05-01" },
  { id: "victoire-2027", nom: "Victoire 1945", date: "2027-05-08" },
  { id: "ascension-2027", nom: "Ascension", date: "2027-05-06" },
  { id: "pentecote-2027", nom: "Lundi de Pentecôte", date: "2027-05-17" },
];

// ---------- Paliers pour les phrases punchy ----------
export const PALIERS = [
  { id: "long", label: "Plus de 30 jours", min: 31, max: Infinity },
  { id: "moyen", label: "15 à 30 jours", min: 15, max: 30 },
  { id: "court", label: "5 à 14 jours", min: 5, max: 14 },
  { id: "tres-court", label: "1 à 4 jours", min: 1, max: 4 },
  { id: "jour-j", label: "Jour J / en vacances", min: 0, max: 0 },
];

export function palierPour(joursTravailRestants, enVacances) {
  if (enVacances) return "jour-j";
  if (joursTravailRestants <= 0) return "jour-j";
  if (joursTravailRestants <= 4) return "tres-court";
  if (joursTravailRestants <= 14) return "court";
  if (joursTravailRestants <= 30) return "moyen";
  return "long";
}

// ---------- Contenu par défaut (seed) : phrases punchy ----------
export const PHRASES_DEFAUT = [
  // long (>30 jours)
  ["long", "La ligne d'arrivée existe, promis. On ne la voit juste pas encore."],
  ["long", "Patience, jeune padawan des copies à corriger."],
  ["long", "Le compteur tourne. Lentement. Très lentement."],
  ["long", "C'est un marathon, pas un sprint. Enfin, surtout un marathon."],
  ["long", "Encore de la route, mais le café tient bon."],
  ["long", "Respire. Bois un café. Recommence."],
  ["long", "On n'est pas rendus, mais on avance."],
  ["long", "La salle des profs t'attend, courage."],
  ["long", "Un jour à la fois, c'est déjà pas mal."],
  ["long", "Le début n'est jamais la partie la plus drôle. Tiens bon."],
  ["long", "Ce n'est pas la mer à boire. C'est juste l'océan."],
  ["long", "Les vacances existent. On te le jure."],
  ["long", "Chaque lundi compte double en fatigue, simple en avancée."],
  ["long", "Ton café du matin est ton meilleur allié cette semaine."],
  ["long", "La motivation, c'est comme le wifi de l'école : ça va, ça vient."],
  ["long", "Un jour d'école de plus, un souvenir marquant de plus (parfois)."],
  ["long", "Le chemin est long mais la destination vaut le coup."],
  ["long", "Pas de panique, le calendrier avance même sans toi."],
  ["long", "Les vacances ne sont pas une légende urbaine."],
  ["long", "Encore un effort et le mois sera passé."],
  // moyen (15-30 jours)
  ["moyen", "On commence à sentir l'odeur des vacances."],
  ["moyen", "Le bout du tunnel a une lumière. Faible, mais là."],
  ["moyen", "Plus que deux ou trois semaines de sonneries."],
  ["moyen", "Ton corps commence déjà à rêver de grasses matinées."],
  ["moyen", "L'agenda se vide doucement de tes excuses pour tenir."],
  ["moyen", "On approche de la dernière ligne droite... presque."],
  ["moyen", "Le compte à rebours devient officiellement excitant."],
  ["moyen", "Les copies s'accumulent, mais les vacances aussi se rapprochent."],
  ["moyen", "Tiens bon, le calendrier ne triche pas."],
  ["moyen", "Chaque semaine qui passe est une victoire silencieuse."],
  ["moyen", "Le sprint final n'a pas encore commencé, mais il chauffe."],
  ["moyen", "Ta valise mentale est déjà à moitié faite."],
  ["moyen", "Plus proche que loin, dirait un optimiste raisonnable."],
  ["moyen", "Les vacances passent du statut « rêve » à « projet concret »."],
  ["moyen", "Bientôt, ce sera toi qui donneras les devoirs de vacances à personne."],
  ["moyen", "Le stress diminue, l'impatience augmente : équilibre parfait."],
  ["moyen", "On sent que la machine ralentit un peu, comme toi."],
  ["moyen", "Les pauses café deviennent stratégiques."],
  ["moyen", "Une lumière au bout du couloir de la salle des profs."],
  ["moyen", "Ça sent bon le repos à l'horizon."],
  // court (5-14 jours)
  ["court", "Le sprint final est officiellement lancé."],
  ["court", "Compte tes jours sur les doigts d'une main (et demi)."],
  ["court", "Tu peux commencer à sourire sans te forcer."],
  ["court", "Les vacances ne sont plus un mirage, c'est presque réel."],
  ["court", "Plus que quelques réveils difficiles à survivre."],
  ["court", "Ton énergie remonte, comme par magie."],
  ["court", "On commence à parler destination vacances en salle des profs."],
  ["court", "Le compte à rebours devient un jeu amusant, pas une torture."],
  ["court", "Chaque journée passée est une mini-victoire savoureuse."],
  ["court", "Tu vois enfin la ligne d'arrivée sans plisser les yeux."],
  ["court", "Les élèves aussi sentent que ça approche (et ça se voit)."],
  ["court", "Le rythme s'accélère, comme ton envie de dormir."],
  ["court", "Encore un peu et le cartable prendra des vacances aussi."],
  ["court", "Les emails professionnels deviennent plus courts, comme ta patience."],
  ["court", "Le compte à rebours passe en mode « excitation contrôlée »."],
  ["court", "Bientôt, ton réveil ne sonnera plus (ou presque)."],
  ["court", "Tu commences à faire des plans pour ton premier jour off."],
  ["court", "Le sourire revient, la fatigue aussi, mais qu'importe."],
  ["court", "C'est le moment où même le lundi paraît supportable."],
  ["court", "Les vacances passent en mode « compte à rebours officiel »."],
  // tres-court (1-4 jours)
  ["tres-court", "C'est l'heure du sprint final, chausse tes baskets mentales."],
  ["tres-court", "Demain sera peut-être ton dernier réveil forcé avant un moment."],
  ["tres-court", "Le compte à rebours devient une compétition avec toi-même."],
  ["tres-court", "Tiens bon, la ligne d'arrivée te fait de grands signes."],
  ["tres-court", "On y est presque, ne relâche rien maintenant."],
  ["tres-court", "Plus que quelques heures de cours et c'est bouclé."],
  ["tres-court", "Ton énergie de dernière ligne droite, utilise-la à fond."],
  ["tres-court", "Le compte à rebours n'a jamais été aussi excitant."],
  ["tres-court", "C'est le dernier virage avant la ligne droite du repos."],
  ["tres-court", "Ce soir, ton oreiller va enfin te dire merci."],
  ["tres-court", "Les élèves comptent les heures autant que toi, avoue."],
  ["tres-court", "Demain, tu pourras enfin ranger l'agenda avec le sourire."],
  ["tres-court", "On sent l'adrénaline monter, et ce n'est pas pour un contrôle."],
  ["tres-court", "Le compte à rebours passe en mode « urgent et joyeux »."],
  ["tres-court", "Plus qu'un dernier effort et tu es libre."],
  ["tres-court", "Ton cerveau est déjà en vacances, ton corps suit bientôt."],
  ["tres-court", "C'est la dernière ligne droite, ne trébuche pas maintenant."],
  ["tres-court", "Bientôt, plus de sonnerie pour te dicter ta journée."],
  ["tres-court", "Les copies attendront, les vacances non."],
  ["tres-court", "Demain ou après-demain, la liberté frappe à la porte."],
  // jour-j
  ["jour-j", "C'est le grand jour, savoure chaque seconde."],
  ["jour-j", "Zéro jour de travail devant toi, tout un monde de possibles."],
  ["jour-j", "Officiellement en vacances, officiellement heureux."],
  ["jour-j", "Le compte à rebours est terminé, place au repos mérité."],
  ["jour-j", "Range l'agenda, sors le maillot ou la couette, au choix."],
  ["jour-j", "Tu l'as fait. Bravo. Maintenant, ne pense plus à rien."],
  ["jour-j", "Le réveil peut sonner à n'importe quelle heure, tu t'en fiches."],
  ["jour-j", "Mission accomplie, vacances activées."],
  ["jour-j", "Plus de copies, plus de sonneries, plus de stress. Juste toi."],
  ["jour-j", "Le compteur est à zéro, ton sourire est au maximum."],
  ["jour-j", "Bienvenue dans la dimension parallèle du farniente."],
  ["jour-j", "Tu as gagné le droit de ne rien faire d'utile aujourd'hui."],
  ["jour-j", "Les vacances sont là, et elles n'ont pas menti."],
  ["jour-j", "Aujourd'hui, ton seul devoir : te reposer."],
  ["jour-j", "Le compte à rebours cède la place au compte à rebours inverse (trop vite déjà)."],
  ["jour-j", "Profite, tu l'as amplement mérité."],
  ["jour-j", "Le silence du matin sans réveil, ça n'a pas de prix."],
  ["jour-j", "Tu peux enfin répondre « rien » quand on te demande ton programme."],
  ["jour-j", "Vacances activées, stress désactivé."],
  ["jour-j", "Bravo, champion des salles de classe, à toi le repos."],
];

// ---------- Contenu par défaut (seed) : devinettes ----------
export const DEVINETTES_DEFAUT = [
  ["Qu'est-ce qui a des dents mais ne mord jamais ?", "Un peigne."],
  ["Qu'est-ce qui monte et descend sans jamais bouger ?", "Un escalier."],
  ["Je n'ai pas de bouche mais je parle, pas d'oreilles mais j'entends. Qui suis-je ?", "Un écho."],
  ["Plus on m'enlève de matière, plus je grandis. Que suis-je ?", "Un trou."],
  ["Qu'est-ce qui a un cou mais pas de tête ?", "Une bouteille."],
  ["Qu'est-ce qui a une aiguille mais ne coud jamais ?", "Une horloge."],
  ["Plus je suis chaude, plus je suis fraîche. Qui suis-je ?", "Une nouvelle."],
  ["Je vole sans ailes, je pleure sans yeux. Qui suis-je ?", "Un nuage."],
  ["Qu'est-ce qui appartient à toi mais que les autres utilisent plus que toi ?", "Ton prénom."],
  ["Qu'est-ce qu'on casse en le nommant ?", "Le silence."],
  ["Je suis pleine de trous mais je retiens l'eau. Qui suis-je ?", "Une éponge."],
  ["Qu'est-ce qui a des clés mais n'ouvre aucune porte ?", "Un piano."],
  ["Plus je sèche, plus je suis mouillée. Qui suis-je ?", "Une serviette."],
  ["Qu'est-ce qui a quatre doigts et un pouce mais n'est pas une main ?", "Un gant."],
  ["Je n'ai ni vie ni souffle, mais je peux mourir. Qui suis-je ?", "Une pile."],
  ["Qu'est-ce qui a des pages mais n'est pas un livre ?", "Un agenda."],
  ["Plus il y en a, moins on y voit. Qu'est-ce que c'est ?", "Le brouillard."],
  ["Qu'est-ce qui voyage autour du monde en restant dans un coin ?", "Un timbre."],
  ["Je tombe souvent mais je ne me fais jamais mal. Qui suis-je ?", "La nuit."],
  ["Qu'est-ce qui a un anneau mais pas de doigt ?", "Un téléphone qui sonne."],
  ["Je grandis quand on me nourrit d'air. Qui suis-je ?", "Un feu."],
  ["Qu'est-ce qui est toujours devant toi mais qu'on ne peut jamais voir ?", "L'avenir."],
  ["Je peux traverser le verre sans le casser. Qui suis-je ?", "La lumière."],
  ["Qu'est-ce qui a un lit mais ne dort jamais ?", "Une rivière."],
  ["Plus on me partage, plus je grandis. Qui suis-je ?", "Le savoir."],
  ["Qu'est-ce qui a des feuilles mais n'est pas un arbre ?", "Un livre."],
  ["Je n'ai pas de jambes mais je cours toujours. Qui suis-je ?", "Le temps."],
  ["Qu'est-ce qui a une tête, une queue, mais pas de corps ?", "Une pièce de monnaie."],
  ["Je disparais dès qu'on dit mon nom. Qui suis-je ?", "Le silence."],
  ["Qu'est-ce qui n'a ni début ni fin ?", "Un cercle."],
  ["Plus on me trempe, plus je deviens sec. Qui suis-je ?", "Une serviette de bain."],
  ["Qu'est-ce qu'on trouve une fois dans une minute, deux fois dans un moment, mais jamais dans mille ans ?", "La lettre M."],
  ["Je suis léger comme une plume, mais même le plus fort ne peut me tenir longtemps. Qui suis-je ?", "Le souffle."],
  ["Qu'est-ce qui a des yeux mais ne voit pas ?", "Une pomme de terre."],
  ["Plus je suis vieux, plus je vaux cher. Qui suis-je ?", "Le vin."],
  ["Qu'est-ce qui ne pèse rien mais que personne ne peut porter longtemps ?", "Une respiration retenue."],
  ["Je suis toujours en train de courir mais je ne bouge jamais. Qui suis-je ?", "Une horloge."],
  ["Qu'est-ce qui a un cœur qui ne bat pas ?", "Un artichaut."],
  ["Je peux être cassé sans être touché. Qui suis-je ?", "Une promesse."],
  ["Qu'est-ce qui a beaucoup de dents mais ne mâche jamais ?", "Une scie."],
  ["Plus on me construit, moins je suis grand. Qui suis-je ?", "Un trou."],
  ["Qu'est-ce qui reste dans un coin mais voyage le monde entier ?", "Un timbre."],
  ["Je suis noir quand tu m'achètes, rouge quand tu m'utilises, et gris quand tu me jettes. Qui suis-je ?", "Le charbon."],
  ["Qu'est-ce qui a une langue mais ne parle jamais ?", "Une chaussure."],
  ["Plus tu en prends, plus tu en laisses derrière toi. Qui suis-je ?", "Des pas."],
  ["Je suis rempli de clés mais je n'ouvre aucune serrure. Qui suis-je ?", "Un clavier."],
  ["Qu'est-ce qui monte quand la pluie descend ?", "Un parapluie."],
  ["Je suis toujours devant toi, mais tu ne peux jamais m'attraper. Qui suis-je ?", "Ton ombre au soleil couchant."],
  ["Qu'est-ce qui a cinq doigts mais n'est pas vivant ?", "Un gant."],
  ["Plus j'ai de trous, plus je retiens de choses. Qui suis-je ?", "Un filet."],
  ["Je suis fait de gouttes, mais je peux noyer une ville. Qui suis-je ?", "La pluie."],
  ["Qu'est-ce qui reste immobile en avançant ?", "Une route."],
  ["Je nais dans l'eau et je meurs au vent. Qui suis-je ?", "Une vague."],
  ["Qu'est-ce qui a des ailes mais ne vole jamais ?", "Un moulin."],
  ["Plus je suis grand, moins tu me vois. Qui suis-je ?", "L'obscurité."],
  ["Je suis fait pour être cassé. Qui suis-je ?", "Un œuf."],
  ["Qu'est-ce qui a plusieurs anneaux mais aucune valeur ?", "Une cible de fléchettes."],
  ["Je vis dans un coin mais je vois tout. Qui suis-je ?", "Une caméra."],
  ["Qu'est-ce qui a un visage mais pas de sourire ?", "Une horloge."],
  ["Plus je descends, plus je suis léger. Qui suis-je ?", "Une bougie qui brûle."],
  ["Je peux remplir une pièce sans prendre de place. Qui suis-je ?", "La lumière."],
  ["Qu'est-ce qui a des mains mais ne peut rien attraper ?", "Une horloge."],
  ["Je suis toujours affamé, je dois toujours être nourri. L'eau me tue. Qui suis-je ?", "Le feu."],
  ["Qu'est-ce qui a quatre roues et vole ?", "Un camion-poubelle."],
  ["Je change de forme mais reste toujours moi-même. Qui suis-je ?", "L'eau."],
  ["Qu'est-ce qui a un toit mais pas de murs ?", "Un champignon."],
  ["Plus tu m'utilises, plus je m'use, mais je ne disparais jamais vraiment. Qui suis-je ?", "Un chemin."],
  ["Je suis dans le ciel le jour, mais invisible. Qui suis-je ?", "Les étoiles."],
  ["Qu'est-ce qui a un nez mais ne sent rien ?", "Une théière."],
  ["Plus je suis plein, plus je suis léger. Qui suis-je ?", "Un ballon."],
  ["Je peux être long ou court, gagné ou perdu, mais jamais touché. Qui suis-je ?", "Le temps."],
  ["Qu'est-ce qui a des bras mais ne peut rien serrer ?", "Un fauteuil."],
  ["Je suis noir, blanc et rouge partout. Qui suis-je ?", "Un journal."],
  ["Qu'est-ce qui a un pied mais ne marche jamais ?", "Un verre à pied."],
  ["Plus tu m'ajoutes de couches, plus je deviens petit. Qui suis-je ?", "Un oignon."],
  ["Je suis capturé mais jamais enfermé. Qui suis-je ?", "Un moment, en photo."],
  ["Qu'est-ce qui a un dos mais ne peut pas s'allonger ?", "Une chaise."],
  ["Je disparais à la lumière du jour. Qui suis-je ?", "Un rêve."],
  ["Qu'est-ce qui a des dents mais qu'on ne brosse jamais ?", "Une fourchette."],
  ["Plus je vieillis, plus je raconte d'histoires. Qui suis-je ?", "Un arbre, par ses cernes."],
  ["Je suis dans chaque pièce mais on ne me voit jamais vraiment. Qui suis-je ?", "L'air."],
  ["Qu'est-ce qui a des yeux fermés en plein jour ?", "Une pomme de terre germée."],
  ["Plus je suis serré, plus je grince. Qui suis-je ?", "Une chaussure neuve."],
  ["Je suis toujours devant, jamais derrière. Qui suis-je ?", "Le futur."],
  ["Qu'est-ce qui a un ventre mais jamais faim ?", "Une bouteille."],
  ["Plus tu me poses de questions, plus je te réponds la même chose. Qui suis-je ?", "Un écho."],
  ["Je suis rond mais je n'ai pas de coins, je roule mais je ne marche pas. Qui suis-je ?", "Une roue."],
  ["Qu'est-ce qui a des feuilles en toute saison ?", "Un cahier."],
  ["Je suis toujours en mouvement, même immobile. Qui suis-je ?", "La Terre."],
  ["Qu'est-ce qui a un cœur mais pas de sentiments ?", "Une carte à jouer."],
  ["Plus je suis vide, plus je résonne fort. Qui suis-je ?", "Un tonneau."],
  ["Je suis fait pour tomber mais on me ramasse toujours. Qui suis-je ?", "Une feuille d'automne."],
  ["Qu'est-ce qui a une couronne mais n'est pas un roi ?", "Une dent."],
  ["Je grandis vers le bas. Qui suis-je ?", "Une stalactite."],
  ["Qu'est-ce qui a des ailes et n'est pas un oiseau ?", "Un avion."],
  ["Plus je suis mince, plus je coupe bien. Qui suis-je ?", "Un couteau."],
  ["Je suis fait de mots mais je ne parle jamais seul. Qui suis-je ?", "Un livre."],
  ["Qu'est-ce qui a un jardin mais aucune fleur ?", "Un jardin d'enfants."],
  ["Je vis une seconde, puis je disparais pour toujours. Qui suis-je ?", "L'instant présent."],
  ["Qu'est-ce qui compte les jours pour toi sans jamais se plaindre ?", "Un calendrier."],
];

// ---------- Contenu par défaut (seed) : blagues ----------
export const BLAGUES_DEFAUT = [
  "Pourquoi les poissons détestent l'ordinateur ? Parce qu'ils ont peur du net.",
  "Qu'est-ce qu'un crocodile qui surveille la Bourse ? Un traderodile.",
  "Deux antennes se marient. La cérémonie n'était pas terrible, mais la réception excellente.",
  "Pourquoi le squelette n'a pas d'amis ? Parce qu'il n'a personne sous la peau.",
  "Qu'est-ce qui est jaune et qui attend ? Jonathan.",
  "Comment appelle-t-on un chat tombé dans un pot de peinture le jour de Noël ? Un chat-peint de Noël.",
  "Pourquoi les plongeurs plongent-ils toujours en arrière et jamais en avant ? Parce que sinon ils tombent dans le bateau.",
  "Qu'est-ce qu'un dinosaure qui dort ? Un dino-somme.",
  "Deux fils électriques discutent. L'un dit : « Ne me touche pas, je suis sous tension ! »",
  "Pourquoi le café porte plainte ? Parce qu'on l'a expresso.",
  "Quel est le comble pour un électricien ? De ne pas être au courant.",
  "Comment appelle-t-on un chien magicien ? Un labra-cadabra.",
  "Pourquoi les mathématiciens confondent Halloween et Noël ? Parce que 31 Oct = 25 Dec.",
  "Qu'est-ce qu'un vampire qui ne fait pas régime ? Un gros-suceur.",
  "Pourquoi le maçon a froid ? Parce qu'il a laissé sa veste en pierre.",
  "Deux tomates traversent la route. L'une se fait écraser, l'autre lui dit : « Ketchup ! »",
  "Quel est le sport préféré des insectes ? Le criquet.",
  "Pourquoi la salade ne se dispute jamais avec le concombre ? Parce qu'elle préfère faire la paix des vinaigrettes.",
  "Comment appelle-t-on un os qui n'aime pas travailler ? Un fainéant squelette.",
  "Qu'est-ce qu'un fantôme en pleine forme ? Un fantô-mieux.",
  "Pourquoi les canards font toujours des bêtises en groupe ? Parce qu'ils sont de mèche.",
  "Quel est le comble pour un jardinier ? De perdre la boule de terre.",
  "Deux œufs se rencontrent. L'un dit à l'autre : « T'as pas l'air dans ton assiette. »",
  "Pourquoi le livre de mathématiques est triste ? Parce qu'il a trop de problèmes.",
  "Comment appelle-t-on un python bâtisseur ? Un serpent maçon.",
  "Qu'est-ce qu'un pingouin en cuisine ? Un chef-froid.",
  "Pourquoi l'ordinateur va chez le médecin ? Parce qu'il a un virus.",
  "Quel est le comble pour un boulanger ? De ne pas être payé en pain.",
  "Deux bananes discutent. L'une dit : « Je ne me sens pas bien. » L'autre répond : « T'as l'air jaune. »",
  "Comment appelle-t-on un chat qui vend des fruits ? Un chat-marchand.",
  "Pourquoi les girafes ont un si long cou ? Parce que leurs pieds sentent mauvais.",
  "Qu'est-ce qu'un mouton qui fait du vélo ? Un mouton à roulettes.",
  "Deux nuages se rencontrent. L'un dit : « Ça va ? » L'autre répond : « Non, j'ai le cafard. »",
  "Pourquoi le poulpe est bon en calcul ? Parce qu'il a huit bras pour compter.",
  "Comment appelle-t-on un requin qui vend des glaces ? Un requin-glaçon.",
  "Quel est le comble pour un opticien ? De ne pas voir venir les problèmes.",
  "Deux escargots se battent. Résultat : un combat au ralenti.",
  "Pourquoi l'abeille se marie toujours en jaune ? Parce qu'elle aime le miel-ange.",
  "Comment appelle-t-on un chien qui fait de la magie ? Un chien-tôt-disparu.",
  "Qu'est-ce qu'un cactus poli ? Un cactus qui ne pique jamais sans dire pardon.",
  "Pourquoi les poules n'aiment pas les maths ? Parce qu'elles préfèrent compter les œufs.",
  "Deux montagnes discutent : « Ça va, t'as l'air en pic forme. »",
  "Comment appelle-t-on un poisson sans yeux ? Un pssn.",
  "Pourquoi le facteur ne se marie jamais ? Parce qu'il a peur de se faire distribuer des reproches.",
  "Quel est le comble pour un professeur d'EPS ? De courir après le temps.",
  "Deux ampoules discutent : « On sort ce soir ? » « Non, je suis grillée. »",
  "Pourquoi les fantômes aiment les ascenseurs ? Parce que ça les relève.",
  "Comment appelle-t-on un chat qui joue au poker ? Un chat-triche.",
  "Qu'est-ce qu'un canard célèbre ? Un canard-star.",
  "Deux pommes de terre discutent : « T'as vu Michel ? » « Non, il est en purée. »",
  "Pourquoi le squelette ne se bat jamais ? Parce qu'il n'a pas le cran.",
  "Comment appelle-t-on un poisson qui joue de la musique ? Un poisson-clown de bal.",
  "Quel est le comble pour un marin ? D'avoir le mal de mer.",
  "Deux chaussettes discutent : « On va où ce soir ? » « Dans la machine, comme d'habitude. »",
  "Pourquoi le zèbre ne se perd jamais ? Parce qu'il a toujours ses rayures avec lui.",
  "Comment appelle-t-on un mouton qui dort ? Un mouton-do.",
  "Qu'est-ce qu'un ours qui n'a pas de dents ? Un ours-en-purée.",
  "Deux nombres discutent : « T'as vu 7 ? » « Non, mais 8 va le manger. »",
  "Pourquoi le pain a peur du grille-pain ? Parce qu'il n'aime pas être grillé.",
  "Comment appelle-t-on un chien détective ? Sherlock Os.",
  "Quel est le comble pour un tailleur ? De perdre le fil de la conversation.",
  "Deux étoiles discutent : « On brille ce soir ? » « Toujours, on n'a pas le choix. »",
  "Pourquoi la vache va sur la Lune ? Pour voir la Voie lactée.",
  "Comment appelle-t-on un lion végétarien ? Un lion peu ordinaire.",
  "Qu'est-ce qu'un scientifique qui n'aime pas son travail ? Un chimiste-triste.",
  "Deux téléphones discutent : « T'as un bon réseau ? » « Ça sonne bien. »",
  "Pourquoi l'horloge est fatiguée le lundi ? Parce qu'elle retourne en arrière tout le week-end.",
  "Comment appelle-t-on un chat pompier ? Un chat-teur d'incendie.",
  "Quel est le comble pour un professeur d'histoire ? De perdre le fil du temps.",
  "Deux fourmis discutent : « On va où ? » « Comme d'habitude, au pique-nique. »",
  "Pourquoi le sapin de Noël n'est jamais en retard ? Parce qu'il perd toujours ses épines à temps.",
  "Comment appelle-t-on un poisson qui fait de la musculation ? Un poisson-costaud.",
  "Qu'est-ce qu'un renard rusé mais poli ? Un renard bien élevé.",
  "Deux chats discutent : « Ça va ? » « Ronron, comme d'habitude. »",
  "Pourquoi le lapin est toujours pressé ? Parce qu'il a un rendez-vous en terrier.",
  "Comment appelle-t-on un ordinateur qui chante ? Un logiciel-karaoké.",
  "Quel est le comble pour un pâtissier ? De perdre la boule.",
  "Deux nuages de pluie discutent : « On se lâche ce soir ? » « Carrément. »",
  "Pourquoi le hibou est bon élève ? Parce qu'il travaille de nuit sans se plaindre.",
  "Comment appelle-t-on un chien qui aboie sous l'eau ? Un chien-mouillé.",
  "Qu'est-ce qu'une sardine qui prend le bus ? Une sardine en boîte, encore.",
  "Deux araignées discutent : « On tisse un plan ce soir ? » « Toujours. »",
  "Pourquoi le fromage ne se partage jamais facilement ? Parce qu'il a du caractère.",
  "Comment appelle-t-on un cheval qui vit à côté de chez toi ? Un voisin-cheval.",
  "Quel est le comble pour un professeur de musique ? De perdre la note.",
  "Deux vagues discutent : « On surfe ce soir ? » « Toujours prêtes. »",
  "Pourquoi l'écureuil est toujours organisé ? Parce qu'il garde tout en réserve.",
  "Comment appelle-t-on un poulet qui fait du théâtre ? Un poulet dramatique.",
  "Qu'est-ce qu'un crabe timide ? Un crabe qui marche de travers pour éviter les regards.",
  "Deux abeilles discutent : « On butine ce soir ? » « Comme toujours. »",
  "Pourquoi le miroir ne ment jamais ? Parce qu'il reflète juste ce qu'il voit.",
  "Comment appelle-t-on un chat qui aime les maths ? Un chat-lculateur.",
  "Quel est le comble pour un professeur de sport ? De ne pas suivre le rythme.",
  "Deux planètes discutent : « Ça tourne ? » « Toujours en rond. »",
  "Pourquoi le hérisson ne se fait jamais de câlin ? Parce qu'il garde ses distances, piquant.",
  "Comment appelle-t-on un poisson chef d'orchestre ? Un poisson-baguette.",
  "Qu'est-ce qu'un nuage optimiste ? Un nuage qui voit toujours le ciel à moitié bleu.",
  "Deux copies d'élèves discutent : « On se corrige quand ? » « Bientôt, en vacances jamais. »",
  "Pourquoi la cloche de l'école est la plus populaire ? Parce que tout le monde l'attend.",
  "Comment appelle-t-on un prof en vacances ? Introuvable, et c'est très bien comme ça.",
  // Blagues mordantes (salle des profs)
  "Pourquoi les réunions pédagogiques n'ont jamais de fin ? Parce que personne n'a le courage de dire « on arrête là ».",
  "Quel est le comble pour un CPE ? Que tout le monde se souvienne de son bureau, jamais de son prénom.",
  "Pourquoi l'inspecteur vient toujours le jour où rien ne va ? Parce que le hasard a un sens de l'humour douteux.",
  "Deux enseignants discutent en salle des profs : « Ça va ? » « Je carbure au café et à l'espoir des vacances. »",
  "Quel est le comble pour un prof principal ? De connaître trente-cinq emplois du temps sauf le sien.",
  "Pourquoi la photocopieuse tombe toujours en panne juste avant le contrôle ? Parce qu'elle aussi a besoin de vacances.",
  "Deux profs discutent : « Le conseil de classe a duré combien de temps ? » « Assez pour que mes cheveux blanchissent un peu plus. »",
  "Quel est le comble pour un prof d'EPS ? De courir toute la journée et de ne jamais arriver à l'heure à la pause.",
  "Pourquoi le vendredi après-midi est le jour le plus long de la semaine ? Parce que le temps aussi a envie du week-end.",
  "Deux collègues discutent : « T'as fini de corriger ? » « J'ai fini par oublier ce que j'ai commencé. »",
  "Quel est le comble pour un surveillant ? De tout voir sauf le bout du tunnel.",
  "Pourquoi la salle des profs est le lieu le plus stratégique du lycée ? Parce que c'est là que se négocient les vraies batailles : la machine à café.",
  "Deux enseignants discutent : « T'as combien d'heures de colle à donner cette semaine ? » « Moins que d'heures de sommeil en retard. »",
  "Quel est le comble pour un principal-adjoint ? D'arbitrer des conflits toute la journée et de perdre le sien contre son agenda.",
  "Pourquoi les vacances scolaires sont si courtes ? Pour laisser le temps de rêver plus longtemps qu'on ne se repose.",
  "Deux profs discutent : « Alors, ce stage de formation ? » « Long comme un lundi, utile comme un mardi. »",
  "Quel est le comble pour un documentaliste ? De tout ranger sauf le temps qui file.",
  "Pourquoi le bulletin trimestriel est redouté par tout le monde ? Parce qu'il ne ment jamais, contrairement aux excuses.",
  "Deux collègues discutent : « Le self, aujourd'hui, comment c'était ? » « Comme d'habitude : mystérieux mais chaud. »",
  "Quel est le comble pour un prof remplaçant ? De connaître vingt salles de classe et aucune par cœur.",
  "Pourquoi les élèves regardent toujours l'horloge cinq minutes avant la fin ? Parce que même à quinze ans, on sait reconnaître une fin de calvaire qui approche.",
  "Deux profs discutent : « T'as survécu à la réunion parents-profs ? » « Disons que j'ai des choses à raconter à la machine à café pendant un moment. »",
  "Quel est le comble pour un gestionnaire d'établissement ? De faire des économies partout sauf sur ses cheveux gris.",
  "Pourquoi le mois de juin est le plus long de l'année scolaire ? Parce que l'attente des vacances ralentit le temps lui-même.",
  "Deux collègues discutent : « Tu tiens le coup ? » « Je tiens surtout la tasse de café à deux mains. »",
  "Quel est le comble pour un prof de français ? De corriger les fautes toute la journée et d'oublier les siennes le soir.",
  "Pourquoi la sonnerie de fin de journée est le plus beau son du monde ? Parce qu'elle ne demande jamais rien en retour.",
  "Deux enseignants discutent : « T'as combien de copies à corriger ce week-end ? » « Assez pour annuler le week-end. »",
  "Quel est le comble pour un prof en semaine de la rentrée ? D'avoir déjà hâte des prochaines vacances dès le premier jour.",
  "Pourquoi les vacances d'été sont les plus attendues de toutes ? Parce qu'aucune autre ne promet autant en si peu de mots : « c'est fini, respire ».",
];
